name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (major.minor.patch, without the v)"
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.inputs.version }}

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  pack:
    needs: build
    uses: ./.github/workflows/pack.yml
    secrets: inherit

  release:
    needs:
      - test
      - pack

    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: src

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          body: write the changelog you lazy fuk
          draft: true
          prerelease: false

      - name: Upload release assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: src/assets
